[package]
name = "krabka-metadata"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Versioned metadata record types + immutable image for Krabka"
repository = "https://github.com/robot-head/crabka"
homepage = "https://github.com/robot-head/crabka"
documentation = "https://docs.rs/krabka-metadata"
readme = "README.md"
keywords = ["kafka", "metadata", "kraft", "krabka"]
categories = ["data-structures", "encoding"]

[lints]
workspace = true

[dependencies]
assert2 = { workspace = true }
wincode = { workspace = true }
serde-wincode = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
krabka-protocol = { version = "0.4.0", path = "../protocol", default-features = false }
krabka-voters = { version = "0.4.0", path = "../voters" }
krabka-ids = { version = "0.4.0", path = "../ids" }
thiserror = { workspace = true }
uuid = { workspace = true }
krabka-security = { workspace = true }
krabka-units = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mutants = { workspace = true }
proptest = { workspace = true }
criterion = { version = "5.0.1", package = "codspeed-criterion-compat" }

[[bench]]
name = "image"
harness = false
