// AUTO-GENERATED by krabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/VoteResponse.owned.rs"
));
#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(msg: &VoteResponse, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert!(msg.encoded_len(v) == buf.len());
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = VoteResponse::decode(&mut cur, v).unwrap();
        assert!(cur.is_empty());
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert!(&reencoded[..] == &bytes[..]);
        let _ = default_json(v);
    }
    #[test]
    fn default_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&VoteResponse::default(), v);
        }
    }
    #[test]
    fn populated_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&VoteResponse::populated(v), v);
        }
    }
    #[test]
    fn tagged_fixture_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&tagged_fixture(), v);
            assert!(tagged_fixture_json(v).is_object());
        }
        let encode = |msg: &VoteResponse| {
            let mut buf = BytesMut::new();
            msg.encode(&mut buf, MAX_VERSION).unwrap();
            buf
        };
        assert!(encode(&tagged_fixture()) != encode(&VoteResponse::default()));
    }
}
