load("//bazel:defs.bzl", "crate_binary", "crate_library", "crate_tests")

package(default_visibility = ["//visibility:public"])

# Consumed by `crate.from_cargo` (see //MODULE.bazel).
exports_files(["Cargo.toml"])

crate_library(name = "kafka-tap")

crate_binary(
    name = "kafka-tap-bin",
    crate_root = "src/main.rs",
    lib = ":kafka-tap",
)

crate_tests(lib = "kafka-tap")
